### PR TITLE
Support insertion of arbitrary license text in generated components a…

### PR DESCRIPTION
**Pull request by cmelion**
…nd pages.

### CODE REVIEW

**Comment by yamalight** [comment]
That's pretty cool, but I have a small comment here: I'd prefer having the injection of license in heading to be optional and behind the question in generator. And maybe using a different license text (not sure about that one). 
Can you please adjust this? And I'll happily merge it. 

And additional smaller thing (which is not necessary):
Maybe rename "license.txt" be just "LICENSE"? Or convert it to "LICENSE.md" for better display on github?

**Comment by cmelion** [comment]
For simplicity, what about leaving the file empty, or perhaps "/*\* insert header/license text here */" .  If the project has a standard header for javascript, the file can be edited after the initial app generation.  Not even sure if LICENSE is the right thing to name it, suggestions are welcome ;-)

Since the intent is to inject this into javascript files, LICENSE works (I think LICENSE.md would work fine as well), originally I was trying to use require and needed a file extension to associate with string type, so that's the only reason I chose .txt.

var fs = require('fs');

require.extensions['.txt'] = function (module, filename) {
    module.exports = fs.readFileSync(filename, 'utf8');
};

var words = require("./words.txt");

**Comment by yamalight** [comment]
But editing file after generation wouldn't change the headers everywhere, right? Or am I missing the point here?

IMO, to give the most flexibility, I'd say it'd best to ask user during generation:
1. If he wants to have file headers (I usually prefer not to)
2. If he wants to have a typical license (give a choice of several most popular ones, e.g. MIT, GPL, etc) or whether he wants to have the license replace with his own (then he has to provide full file path to his text)

**Comment by cmelion** [comment]
Some background:
One of the comments provided on a PR for a current Turris-generated project I'm working on was to remove the //react comment from all the generated files.  The suggestion was to replace it with our standard corporate disclaimer/proprietary/legal verbiage, but this could be anything or nothing.  If you don't want anything in the header, it's simple enough just to leave the license/header template blank or even put //react in it ;-) . 

The changes I made only affect files generated using turris:component and turris:page generators since this is relatively easy to do and has the most impact on ongoing maintenance.  Anything more elaborate creates a chicken and the egg scenario and IMHO overly complicates the (typically) one time application of "yo turris".

**Comment by cmelion** [comment]
"IMO, to give the most flexibility, I'd say it'd best to ask user during generation:
1. If he wants to have file headers (I usually prefer not to)
2. If he wants to have a typical license (give a choice of several most popular ones, e.g. MIT, GPL, etc) or whether he wants to have the license replace with his own (then he has to provide full file path to his text)"

Yes that is the most flexible approach, do you have time to implement it?

Would the questions be asked every time a new component/page is generated, or would it remember?

It's also worth noting that too many variables and questions may discourage use of generators on an ongoing basis.

**Comment by cmelion** [comment]
"But editing file after generation wouldn't change the headers everywhere, right? Or am I missing the point here?"

I think you are more concerned with the initial project generation and I'm more interested in what happens afterwards.

During app generation much of the boiler-plate code will either be deleted, edited or replaced (for example the "other" route will in most cases be immediately deleted or renamed by the project architect/lead).   I'm more concerned with encouraging other developers, who may come much later, to adhere to conventions and use generators instead of copy-paste.  I want to provide incentives to NOT copy-paste or introduce personal coding conventions; give them stuff, like auto generation of unit tests, mocks, css, jsx and js with appropriate naming conventions, locations and defaults.  My experience with generators is that many developers become annoyed when asked the same questions over and over, and like most users, the fewer clicks/keystrokes, the better.

**Comment by yamalight** [comment]
Oh, you are right, for some reason I thought about initial generation. Now that I'm looking at the code, I see that you indeed added headers stuff to page/component.
Then, yes, let's do it this way - I'll merge your PR and add option to include header during page/component generation myself with some additional configuration possibilities :)

**Comment by cmelion** [comment]
Cool :-)

**Comment by yamalight** [comment]
@cmelion okay, added optional header generation (with custom files support too), pushed and published v0.2.0 to npm!

**Comment by cmelion** [comment]
@yamalight nice!

**Pull request merged**
